### ISSUE TITLE
newrelic_record_custom_event missing

### ISSUE THREAD

**Issue by nnnikolay** [In-Touch/newrelic#17]
Could you please tell me, why  `newrelic_record_custom_event` call is omitted ? Is there any reason for that ? or you just forgot ?

Thanks.

**Comment by localheinz** [comment]
@nnnikolay 

I guess this is why (see https://github.com/In-Touch/newrelic/blob/master/src/Intouch/Newrelic/Newrelic.php#L26):

> This class is designed to work with PHP Agent version 3.1+ and requires PHP 5.3+

@pleckey 

What do you think, shall the whole thing be updated to reflect the latest changes in the NewRelic PHP Agent API?

**Comment by nnnikolay** [comment]
@localheinz Thanks for explanation, I missed that note.
