### ISSUE TITLE
Installation without composer

### ISSUE THREAD

**Issue by bvogel** [In-Touch/newrelic#2]
Hi, how do I install this if I don't use composer?

**Comment by pleckey** [comment]
Hi @bvogel - I've never used eZ-Publish, but based on the ezpublish-newrelic code you would simply need to require the file as @vutran suggested (just the `require_once` line, not the others) somewhere before ezpublish-newrelic is loaded.

As you can see from the ezpublish-newrelic source:
https://github.com/killerwolf/ezpublish-newrelic/blob/develop/classes/newrelichandler.php#L3

It expects the class the be available on load; which you can accomplish manually or with autoloading, depending on how eZ-Publish itself works (which I really have no knowledge of, sorry).
